### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by stringparser** [stringparser/artist-carpenter-berlin#2]
- [x] Change font to [PT Sans](https://fonts.google.com/specimen/PT+Sans)
- [x] Location Support -> Big Build
- [x] Custom Objects -> Small build
- [x] Add navigation bar to other pages

Sent by email

![image](https://user-images.githubusercontent.com/7457705/43396218-305c1e1c-9401-11e8-9b00-69f8554c8e39.png)

**Comment by andymasoner** [comment]
nice
