### ISSUE TITLE
Index homepage

### ISSUE THREAD

**Issue by andymasoner** [stringparser/artist-carpenter-berlin#3]
- [x] Logo should be larger
- [x] Font should be larger
- ~~~add parallax animation between sections~~~
- [x] On a screen the text and logo should fill the screen - to reveal the content you scroll down
Navigiation bar is good but only should be displayed on other pages, not home page
When you scroll the Plinth, Small build and big build content should scroll over the opening text panel - not a big thing, just thought its a nicer design element

**Comment by andymasoner** [comment]
Logo to be moved up with text 2 lines (lines meaning text below) think it will make it look more centred on page

**Comment by stringparser** [comment]
Ok, fill fix. 

Will also add the parallax tomorrow and see what's your opinion on it (either to keep it or not).
